### PR TITLE
Change the file creation to be 'kickstart::file::advanced' defined type.

### PR DESCRIPTION
**Pull request by rnelson0**
Add new 'kickstart::file::simple', that provides many sane defaults for users with less kickstart knowledge.
Update defaults from CentOS 6 to CentOS 7.

### CODE REVIEW

**Comment by rnelson0** [comment]
Replaces #1

**Comment by danzilio** [comment]
I'm conflicted here. I like what you've done, but I've got some questions:

- do we really need another template?
- couldn't `kickstart::files::simple` be achieved by wrapping `kickstart::files::advanced`?
- doesn't `kickstart::files::simple` really belong in a profile?
- could we move `kickstart::files::simple` to an example?

I don't want to detract from the focus of this module being to provide primitives for building kickstarts. I'd much rather the kickstart resource remain `kickstart` by name as it is intended to be the first-class citizen in this module.

**Comment by rnelson0** [comment]
For posterity, a recap of IRC discussions:

Here's [a gist](https://gist.github.com/rnelson0/f253967a83b9a6d60589) of my component and profile classes now, where `kickstart::ks_file` would be equivalent to `kickstart::file::simple` with a few small differences.

I think the `::simple` and `::advanced` file/template COULD be merged, and simple could be a wrapper for advanced. However, my viewpoint is that advanced is for people who know kickstart intimately (not me) and simple is for people who are perfectly fine with cargo cult kickstart files (me!). By making it opinionated and really simple, it eases people into kickstart before they have to learn too much about it. You could simply `kickstart::file::simple{'/path/to/kickstart':}` and have something that works. The advanced version just requires a lot more knowledge. Merging the two may complicate that significantly and may not provide much value, IMO.

As for the service, that could be `kickstart::service` or, as seen in the component module, could just be left to a profile that includes apache/nginx with the right path. That's probably simpler and the more I think about it, the more correct it is. Then the types just need to be `kickstart::simple` and `kickstart::advanced` or something.

**Comment by danzilio** [comment]
OK! I've got it. How about a `kickstart_profiles` module for this kind of thing?

**Comment by rnelson0** [comment]
Bump!

**Comment by rnelson0** [comment]
@danzilio bump!

**Comment by rnelson0** [comment]
This is live at https://github.com/voxpupuli/community_kickstarts now, ditching this. Thanks!

**Pull request closed without merging**
