### PR TITLE
added support for addons

### PR DESCRIPTION
**Pull request by blackophelia**
I needed to create a kickstart config for centos 7, that utilised the %addon section, so have added support for this.

### CODE REVIEW

**Comment by danzilio** [comment]
Thank you @blackophelia for this awesome contribution! I'll admit, I had never heard of the `addon` section until now! Would you be able to provide a functional example for the README? The contrived example you've provided demonstrates the behavior quite well, I'd just prefer to have real examples if possible.

**Comment by blackophelia** [comment]
@danzilio, no probs.  I've got one real-world example, and I'll leave the more detailed contrived example in place.

**Comment by danzilio** [comment]
That works for me! Thank you!!

**Comment by blackophelia** [comment]
Thanks!  Just realised I haven't updated the changelog/metadata.json with a new version.  Shall I?

**Comment by danzilio** [comment]
That's ok! I usually do that when I cut a release. I'll do that now!

**Comment by blackophelia** [comment]
Awesome :)

**Comment by danzilio** [comment]
Just released `0.3.0` to the Forge! Thank you!!

**Pull request merged**
